name: Importar plantilla

on:
  push:
    paths:
      - github-source.tar.gz

permissions:
  contents: write

jobs:
  importar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extraer código fuente
        run: |
          tar -xzf github-source.tar.gz
          rm github-source.tar.gz
      - name: Guardar plantilla completa
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Importar plantilla completa"
          git push
